### ISSUE TITLE
Request to fix the problem UI

### ISSUE THREAD

**Issue by reysonk** [tyfon7/UIFixes#10]
**Can you fix these things?**

In the corner of combat glory, if you click sort, the UI freezes (Eternal loading of inventory).

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/302f07b3-0445-47d9-813e-27133a98d994)

If you use mod "MoreCheckmarks", then items without armor points display armor instead of a tooltip
Exp item : https://tarkov-market.com/item/stich_profi_chimera_boonie_hat

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/bc26aebb-8687-4c6a-8bb1-6879ef1e277f)

**Comment by tyfon7** [comment]
No idea what's going on with the first issue - have you got some other mod affecting that? The hideout icon doesn't normally appear below the sort button like that...

Second issue actually is a BSG bug, I think i have a fix.

**Comment by reysonk** [comment]
The fact that the shelter icon [is normal](https://hub.sp-tarkov.com/files/file/1781-inventory-organizing-features-3-8-0-senko-edition-fix/) :) 
Pressing this sort button on the Battle Glory Angle screen (indicated by an arrow) causes the inventory to freeze.
**The task is to hide this button on the battle glory screen** :)

[source](https://github.com/seionmoya/iof)
![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/3c87bb04-a66b-4e73-a5d0-4765e90a7f4a)

**Comment by tyfon7** [comment]
I'm confused. If that's added by another mod, why are you opening an issue here? Talk to that modder.
