### ISSUE TITLE
Move window button is covering the sort button.

### ISSUE THREAD

**Issue by DEV-024** [tyfon7/UIFixes#12]
Sort button not appearing in containers. 

It seemed to fix itself randomly on one of my alt+tabs out and into the program, not sure but I still wanna post this in case it happens again or maybe there is somethin up in the code idk.

**Comment by tyfon7** [comment]
What kind of container was it?

**Comment by DEV-024** [comment]
> What kind of container was it?

It wouldn't matter what container I picked they all we're missing the sort button

**Comment by tyfon7** [comment]
Hmm... I can't repro and I'm testing with all sorts of containers, with and without tags, etc. 

Let me know if it happens again

**Comment by DEV-024** [comment]
> Hmm... I can't repro and I'm testing with all sorts of containers, with and without tags, etc.
> 
> Let me know if it happens again

hey so I just realised what I did, I was trying to sort while in trader menu (which isnt possible) 

im a little slow... probably good to just delete the post lol

**Comment by tyfon7** [comment]
It's the thought that counts ;)
