### ISSUE TITLE
The repair/ insure menu window appears partially under the screen, when previously we had another window displayed low enough.

### ISSUE THREAD

**Issue by FiveFme** [tyfon7/UIFixes#13]
eg. when opening Backpack> opening Rig> and 'REPAIR'

**Comment by tyfon7** [comment]
It's funny, BSG has a function `CorrectPosition()` that they sprinkle all over their code. Each window calls it 2-3 times as it shows, but they never actually call it after they set the window position. 

Fixed in next release
