### ISSUE TITLE
When an item is completely destroyed, the item cannot be repaired from the flyout menu.

### ISSUE THREAD

**Issue by FiveFme** [tyfon7/UIFixes#15]
Tested only with 'Crossbow tactical glasses'.
[imgur](https://imgur.com/a/7UinN8n)

**Comment by tyfon7** [comment]
Good catch. Their code has a place where it checks a bunch of stuff to generate errors, and broken item is one of them. I missed the part where it disables the repair button if there's an error _except for broken item error_. 🍝

**Comment by tyfon7** [comment]
Fixed in 1.6.6
