### ISSUE TITLE
Request: Fix Turn quest item to trader

### ISSUE THREAD

**Issue by reysonk** [tyfon7/UIFixes#17]
There is a strange error that does not allow you to scroll through the transfer list of items

List of mods to reproduce the problem:
- SPT
- Andrudis QuestManiac Updated

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/5bc7319d-328a-4aa8-b88c-eff489b8ab72)
![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/44e72025-d227-4b91-a324-c5fd2e52ce75)

**Comment by tyfon7** [comment]
BSG never hooked up the scrollarea to its content.

Will be fixed in 1.7.3.

**Comment by reysonk** [comment]
Its so cool! Tnx man
