### ISSUE TITLE
[Feature Req] Sell to context menu item

### ISSUE THREAD

**Issue by Inj3c7i0n** [tyfon7/UIFixes#18]
Hey man, I would like to suggest a context menu item that allows you to Sell to traeders (and possibly flea) with prices. Kinda like your repair menu is.
Here's a video below to explain, but I think that UI design at the end might be harder to code in. 
https://www.youtube.com/shorts/TWJ7Xy5lpEA

**Comment by tyfon7** [comment]
[LootValue](https://hub.sp-tarkov.com/files/file/1606-lootvalue/) does this, albeit without the UI. If I ever added something like this it would likely be a different mod
