### ISSUE TITLE
Can this UI be Fix/Improve?

### ISSUE THREAD

**Issue by SGZ-Creations** [tyfon7/UIFixes#19]
Hey Is this a UI element you can fix or improve?

So i where using SVM to have this happen tho you think there's anything within this that you can do to make the bar stay within the same length as it usually do if it has 100?

![Cursed Durrability Bar](https://github.com/tyfon7/UIFixes/assets/59801736/8889e941-1cd8-470a-a126-b94d9992d28c)

SVM Individual item Change Code:

#Kalashnikov PKM 7.62x54R machine gun
64637076203536ad5600c990:Durability:10000
64637076203536ad5600c990:MaxDurability:10000

**Comment by tyfon7** [comment]
I can keep it from overflowing the window, but I can't make it "accurate"... the client assumes all weapons have 100 maximum possible durability. Technically that's supposed to be read from the template's TemplateDurability field, but in practice the code just has 100 hardcoded everywhere.

**Comment by tyfon7** [comment]
Fixed in next update

**Comment by SGZ-Creations** [comment]
Thanks
