### ISSUE TITLE
Request:  Tags on panel name hide

### ISSUE THREAD

**Issue by reysonk** [tyfon7/UIFixes#20]
Please add a setting that will hide everything that is written in the tags at the top of the container:)

![изображение](https://github.com/tyfon7/UIFixes/assets/26927358/1b5b9e22-fb56-4404-b7a4-48e5e907ed14)

**Comment by tyfon7** [comment]
I assume those tags are from some mod that's the using the tag to store information about the container? I have no way of knowing what comes from a mod and what was entered by the user. 

I suggest asking that mod author to store their data in some other way.

**Comment by tyfon7** [comment]
I see... But that's kind of the point of tags? I believe that you want to get rid of it, but it's not really a *fix*; I'm not doing arbitrary customizations

**Comment by reysonk** [comment]
For a story not to forget GridWindowButtonsPatch.cs
```
            if (wrappedInstance.LootItem.Int32_0 <= 4)  //hide IoF key and TAG
            {
                Transform SortButton = __instance.transform.Find("Caption Panel/Sort Button(Clone)");
                SortButton.gameObject.SetActive(false);

                Transform TagPanel = __instance.transform.Find("Caption Panel/TagText");
                TagPanel.gameObject.SetActive(false);
            }
```
