### ISSUE TITLE
Request: Shortcut to place items on Flea

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#22]
Basically, instead of having to click "PLACE OFFER" you can press Enter, or CTRL+Enter or something along those lines to place the offer. Or even Space so it aligns with traders.

**Comment by LordHarkon** [comment]
And an extra feature, still for flea market, if possible, when pressing K, it automatically adds three 0s at the end of the price.

**Comment by tyfon7** [comment]
First part done. Gonna say no for the second part - it would complicate the code a lot and it's bit esoteric, even if is useful
