### ISSUE TITLE
Feature Request: Extend window resize functionality to other windows in the game

### ISSUE THREAD

**Issue by iTheSailor** [tyfon7/UIFixes#32]
The window resize functionality that is present for the item inspect window...

![image](https://github.com/tyfon7/UIFixes/assets/112807438/5555968e-70f1-4768-91f1-b62c7edc304a)

...would be very useful if extended to the Add Offer window in the flea market, as the Add Offer window always blocks SOME pertinent information, whether that be the quantity of items, or the price of the listing

![image](https://github.com/tyfon7/UIFixes/assets/112807438/55887b27-e47c-4cf0-9a18-bd61d66df07b)

and maybe also the repair window for the sake of continuity and uniformity, I cant think of any other window modules off the top of my head

It's not global UI resizing, but it's something

_--ps thank you for the quick 2.0.2 fix, my heart nearly broke when I thought I had to endure it without this mod for a bit_

**Comment by tyfon7** [comment]
The challenge for the add offer window is not just making it resizable, but what happens when you shrink it. The requirements side could get a little thinner or shorter, though not by much. The stash side can go as short as you like, but not thinner without adding horizontal scrolling - which I'm not sure exists in this game? I can't think of any places that use it...

**Comment by iTheSailor** [comment]
horizontal scrolling exists in the sorting table in stash! :D  

![image](https://github.com/tyfon7/UIFixes/assets/112807438/bd038955-c0c5-474b-a6b6-d67b925d54d8)

**Comment by iTheSailor** [comment]
and the interesting part is it's always there, it just doesn't engage until the space hits a minimum width- which i'm assuming is the actual width of the scroll bar itself. they just jammed an oversized component and said "if they need it's there"

**Comment by tyfon7** [comment]
Oh, the sorting table is even weirder than you think. It's not oversized, it actually grows, a fact that complicates their code immensely. 

But yeah, that's a horizontal scrollbar! So at least it's doable. I'll add it the list.

**Comment by iTheSailor** [comment]
If you end up going through with it and find yourself with an excess of
time, I'd love to get to watch your implementation and workflow- I am
looking to start modding my self soon and am trying to teach myself c#
(python background), i think a tour of what the dev environment looks like
for SPT would be invaluable for me getting upto speed

**Comment by tyfon7** [comment]
Cleaning up old issues  - killing this one as it's simply too much work to be worth it.
