### ISSUE TITLE
Tactical vest compartment looks weird

### ISSUE THREAD

**Issue by ColaMon** [tyfon7/UIFixes#33]
mod version : UI FIXES 2.0.5
![2024-07-11 01-25  (0)](https://github.com/tyfon7/UIFixes/assets/168758729/72213a5b-c63b-415f-bdb7-8b64d596fab7)
![2024-07-11 01-25  (1)](https://github.com/tyfon7/UIFixes/assets/168758729/26ad2e6c-25a4-43b2-8cbb-28842e00fa79)
I don't know why

Restart the game and will be fine.

**Comment by tyfon7** [comment]
Should be finally fixed for real
