### ISSUE TITLE
Feature Request: Navigate Tasks with Arrowkeys

### ISSUE THREAD

**Issue by Icoryx** [tyfon7/UIFixes#34]
Basically what the title says. Probably not a lot of people who would use it but I just noticed myself trying it for Scorpion who got a lot of tasks and being kinda disappointed that it didn't work.

**Comment by tyfon7** [comment]
It's a good idea, but it has the same problem that requests for keybinds to change tabs: the UI is just too slow. You'd want to go down 3 quests, hit down three times, and be lucky if you actually went more than 1. 

Obviously less than ideal, but I don't like adding functionality that ends up feeling bad :(
