### ISSUE TITLE
Feature Request: Option to add back old sorting table button

### ISSUE THREAD

**Issue by Kvan7** [tyfon7/UIFixes#35]
New update, main game, seems to have moved the sorting table opening button to the top. This isn't that bad, (except when i opened a dev profile and the money was clipping into the button but thats just a rich people problem). 

I'm wondering if it would be possible to add back the old button as well. Just like an option to re-enable it would be cool. I just have much muscle memory of going down there to open it and now its gone. This wouldn't be a problem if i used the `shift+click` opens sorting but i like the multiselect so much. I do understand why it likely got removed as having it that close to the sort button could be a bad UI choice, but I know I am fine with that risk. I do know you are really busy ensuring the cultists don't resurrect the mangled grid bug, so if this is possible not really as urgent as killing the cultists but would be a nice to have. 

Also it would be more work but ideally this could be a dropdown and have options [new button, old button, both buttons], as i kinda also want the new one gone completely, but that is much more a personal pref.

**Comment by tyfon7** [comment]
In next release

**Comment by tyfon7** [comment]
Released
