### ISSUE TITLE
Feature Request: Make Sort/Stack work with custom stackable types

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#38]
A button in containers that will stack items that can be stacked. This for both in and out of raid.

For example, you have this:
![image](https://github.com/user-attachments/assets/86849e7b-f326-4a9d-b0a3-75fc76cb97cd)
And after pressing the button, you'll have this:
![image](https://github.com/user-attachments/assets/c595eebf-ffb4-493e-b501-dbb30bccf335)

**Comment by tyfon7** [comment]
Sort button doesn't do what you want?

**Comment by LordHarkon** [comment]
It only does it for vanilla stack sizes. I have a mod that modifies the stack sizes for some item that did not have a stack size previously, and it doesn't work for those.
This is the mod: https://hub.sp-tarkov.com/files/file/2146-spt-bss-better-stack-size

**Comment by tyfon7** [comment]
Fixed in next release. Made the general stack logic work with custom stackable items, too - i.e. dragging such items over a container that already contains some will stack them.
