### ISSUE TITLE
Issue [2.3.1]: Ammo Boxes Aren't Unpacking

### ISSUE THREAD

**Issue by Akrotluv** [tyfon7/UIFixes#39]
Hey Tyfon; since the 2.3.1 update, any ammo box I try to unpack is acting like I didn't try to unpack it; it's neither giving ammo nor being deleted, just stays there whether it's in-raid or out of raid. Seems the code to replace the packet with the ammo item has broken the whole thing...

**Comment by tyfon7** [comment]
Are you using Fika? I've heard the ammo box unload-in-place doesn't work with fika...

**Comment by tyfon7** [comment]
Also if there's any errors in the console (hit ~ in game) or in the server output, that would be helpful to see

**Comment by Akrotluv** [comment]
Nah, no FIKA or any other co-op mod. The weirdest thing is that there are no errors in neither console nor in the server output. Error log however does throw an inventory error, so uploading the three standard logs for ya.
[2024.07.24_3-07-44_0.14.9.1.30626 errors.log](https://github.com/user-attachments/files/16356612/2024.07.24_3-07-44_0.14.9.1.30626.errors.log)
[LogOutput.log](https://github.com/user-attachments/files/16356618/LogOutput.log)
[server-2024-07-24.log](https://github.com/user-attachments/files/16356620/server-2024-07-24.log)

**Comment by tyfon7** [comment]
Fixed in latest, please let me know if you still see issues.

**Comment by Akrotluv** [comment]
Hate to do this, but unfortunately nope, this hasn't been fixed for me.
The new toggle option and disabling the in-place option allows ammo boxes to unpack like normal, but with it enabled (by default it is), I'm still getting the same situation as before, boxes not unpacking nor acting like they've been unpacked and remaining in the same spot and still full of ammo. Still no error in terminal nor in-game :\

**Comment by tyfon7** [comment]
Are you seeing this as host or client?

**Comment by tyfon7** [comment]
Managed to get a repro as client, I think this resolves it, but frankly not confident. Give it a shot and let me know? https://github.com/tyfon7/UIFixes/releases/tag/v2.3.4

**Comment by Akrotluv** [comment]
Sadly, nope, didn't change a thing.

And I presume I'm trying as a host, because dunno man, just a typical, single-player SPT installation from my own PC, nothing fancier.

**Comment by tyfon7** [comment]
Ah, got you mixed up with a fika user who also was seeing issues.

**Comment by Akrotluv** [comment]
v2.3.4 logs are as follows;
[LogOutput.log](https://github.com/user-attachments/files/16390280/LogOutput.log)
[2024.07.26_10-12-10_0.14.9.1.30626 errors.log](https://github.com/user-attachments/files/16390307/2024.07.26_10-12-10_0.14.9.1.30626.errors.log)
[server-2024-07-26.log](https://github.com/user-attachments/files/16390299/server-2024-07-26.log)

**Comment by tyfon7** [comment]
Thanks. I'm kind of stumped... the error appears to be that it can't find space in the temporary stash I create to hold the ammo box while it unloads. But that shouldn't be possible. Your error log is full of a lot of stuff that looks bad - are you having other issues with your game? 

> 331 errors encountered while deserializing profile 669667330002ba7807b43901 

I'm wondering if you just have a corrupted profile :(

**Comment by tyfon7** [comment]
Marking this complete as the issue doesn't repro on a clean profile - if you figure out that it was a mod conflict, lets open a new issue for that
