### ISSUE TITLE
Hotkeying an item and swapping said item with another to the inventory will leave the hotkey to that item.

### ISSUE THREAD

**Issue by FuckingStealingNames** [tyfon7/UIFixes#4]
![EscapeFromTarkov_vTjIQZPOKs](https://github.com/tyfon7/UIFixes/assets/82725256/6e1b7ec5-a7fe-4d61-ba54-421852b1dda5)
First image shows the hotkeyed item, all safe and sound in its inventory... and it gets switched with a food, leaving the hotkeyed item in the inventory, all cold. 
![image](https://github.com/tyfon7/UIFixes/assets/82725256/03a8301b-b711-4d1a-8426-7102bc6fffb8)

This does linger into the raid also, but doesn't seem to have any harmful effects, just that it stays there until you hotkey another item into that slot.

**Comment by tyfon7** [comment]
Nice catch. This sent me down the rabbit hole of how operations raise events to signal that they're done and various stuff needed to happen. Needless to say it's a mess.

This also made me realize that hover state isn't set correctly when you swap - you have to move your mouse out and back over the item to rebind it, for example.

**Comment by tyfon7** [comment]
Fix will be in 1.3.4
