### ISSUE TITLE
Issue [2.3.1]: Multi-Select/Menu Drag Oddity

### ISSUE THREAD

**Issue by Akrotluv** [tyfon7/UIFixes#40]
Hey Tyfon, I just noticed that whenever I try to box-select and my mouse is over the name/button bar of an opened container, I'm able to start doing the drag box, but at the same time the container menu starts fidgeting around like it normally would when being dragged.
Usually UI location would be locked when box dragging, as the box selection takes priority over other UI elements, but however you might fix it or leave it will be fine enough.

**Comment by tyfon7** [comment]
Are you holding shift while doing this? Or have you rebound the selection key to right-mouse, or some other key?

**Comment by Akrotluv** [comment]
Yeah, I'm holding shift while doing this, pretty much default binds for the most part.

**Comment by tyfon7** [comment]
Ok gotcha. 2.3.1 disables item dragging when shift is down, but other dragging still works so it's dragging and drawing. I have a change in 2.3.2 to disable other items dragging when shift is down.
