### ISSUE TITLE
Home/End shouldn't scroll when a textbox is focused

### ISSUE THREAD

**Issue by tyfon7** [tyfon7/UIFixes#41]
Textbox home/end should take priority over scrolling

**Comment by Akrotluv** [comment]
For consistency of standard UX conventions, Page Up/Down should also be blocked from scrolling, but that's up to you Tyfon.
Will add, though, perhaps also make this buttons re-bindable for those who want to use other keys instead?

**Comment by tyfon7** [comment]
The challenge is that PageUp/PageDown are hardcoded deep inside BSG code, and the way I currently fix that is via a harmony transpile patch, which means it's not very flexible.

**Comment by Akrotluv** [comment]
Ya ripper; this works as intended, so unless you want to improve upon the method used, this is pretty much done.
