### ISSUE TITLE
Suggestion: Add mod localization capability

### ISSUE THREAD

**Issue by GoLani11** [tyfon7/UIFixes#43]
Hello! I'm a user who often uses your mode. Many users also use this mode in Korea, but the mode is in English, so it's a little inconvenient to use. 

Do you have any thoughts on adding a localization function?

Of course, I know that there are difficulties in producing it, but if you make it, I think I will use it more comfortably.
And if you add a localization function, I will help you translate Korean.

Grammar can be weird because I'm a little weak in English conversation. Please understand this.
Thank you for updating the mods frequently and thank you for reading this.

**Comment by tyfon7** [comment]
If you mean for UI elements in-game, the only non-localized part is the "Show/Hide Mod Stats" button on the inspect windows, mentioned in #8 

If you mean the settings in the F12 menu, unfortunately those strings get used in the cfg file, which means changing them would lose all your settings. The mouseover descriptions could be localized, though.

Which do you mean (or both?)

**Comment by GoLani11** [comment]
Oh I think the explanation was a bit lacking I'm sorry. It was the F12 part you mentioned.
I'm a beginner in coding and I don't know as well as you, but I got your source code and added a localization function to F12 to code it.

Added one more language tab. By default, English is displayed, and if you choose another language and restart the game, it's changed.

When I tested it, I didn't find any problems except that the Language menu doesn't translate when I change to Korean. However, there can be bugs. As I said above, this point can be because I'm a beginner in coding. Sorry if there is.

I'll leave it as an attached file, so if you're interested, please get it and apply it, and if you think it's okay, I'd appreciate it if you could add it at the next update.

[UIFixes-2.3.4 Translate.zip](https://github.com/user-attachments/files/16402086/UIFixes-2.3.4.Translate.zip)

**Comment by tyfon7** [comment]
While I appreciate the hard work, I don't think that keeping translations of the options menu is sustainable. It prevents me from being able to make changes, and will be constant upkeep.
