### ISSUE TITLE
Feature request: Single click to pick up item in inventory instead of click and drag

### ISSUE THREAD

**Issue by LaserP563** [tyfon7/UIFixes#46]
I apologise if this is a feature already, but I've been experimenting with the different options for an hour and I have yet to come across it if it is. 

My main issue with the Tarkov inventory system is having to hold the mouse button while dragging the mouse to move items. This mod's ability to select multiple items helps, but I think accessibility could be additionally increased by allowing the user to toggle an option in the F12 menu to click once on an item to pick it up, then place the item elsewhere by clicking again. Alternatively, if that idea is somehow not possible, a bindable button in the F12 menu to act as an alternate Mouse 1 so the user can hold down a keyboard button to pick up an item in their inventory instead of having to click and drag with the mouse.

**Comment by tyfon7** [comment]
Anything's possible. The hard part about this is that all the logic for moving an item, showing the item on the cursor, and placing an item are directly connected with Unity's `OnDrag` events. It might be as simple as binding `OnClick` and invoking `OnDrag`, or it might have a bunch of weird side effects. I'll take a look. It's a good suggestion regardless!

**Comment by tyfon7** [comment]
Cleaning up old issues - killing this one as I looked into it and it just breaks too many things in too many places.
