### ISSUE TITLE
Feature Request: Drag magazine on weapon to swap/reload

### ISSUE THREAD

**Issue by B-u-z-z-T** [tyfon7/UIFixes#53]
Ever had e.g. a MCX .300 and M4 at the same time equipped - to not reload the wrong mag and not having to open the weapon window, looking for the mag-slot and drag-and-drop onto it. (extension menu reload, on the mag, chooses the gun randomly, or in order of slots - not sure) To make it easier to implement, i guess it should only work for equipped guns, since else the in-place swap probably will collide with this function.
(Could also be interesting for weapon mod-parts.)

**Comment by tyfon7** [comment]
Implemented in 2.4.5
