### ISSUE TITLE
Feature Request: Prefering the best fitting slot-size

### ISSUE THREAD

**Issue by B-u-z-z-T** [tyfon7/UIFixes#54]
When drag-and-dropping or ctrl-LMB clicking it would be really nice, if it would prefer the best fitting sized slots. e.g. pickung up grenades to the rig and using 1x2 (mag-) slots, or 1x2 mags placed in 2x2, instead of the 1x2 slots to the left.
(if i understood that correctly) Might be easier to implement, when the slots that now are in correct order, because of your mod - this slots-list could be on top be ordered by slot increasing slot size. So the slots-list would be left to right and top to bottom, but for every slotsize. That way the it would always prefer, without further and complicated handeling of the looted item.

**Comment by tyfon7** [comment]
>  So the slots-list would be left to right and top to bottom, but for every slotsize

That's pretty clever. I'll give it a shot

**Comment by tyfon7** [comment]
Implemented in next release

**Comment by B-u-z-z-T** [comment]
> Implemented in next release

Sick - thanks, mate!
