### ISSUE TITLE
Helmet swapping into RAC headset slot on another helmet

### ISSUE THREAD

**Issue by pythonnxx** [tyfon7/UIFixes#6]
If you have an op-score fast Mt headset equipped on a helmet and attempt to attach it to a helmet that cannot equip it, it will swap the headset with the other helmet and you'll have a helmet inside a helmet
![2024-05-26 08-33  (0)](https://github.com/tyfon7/UIFixes/assets/170876600/53bd6c0c-aa05-42b7-84df-78e13fd576b7)

**Comment by tyfon7** [comment]
I can't reproduce this - do you have any other mods installed that might be relaxing some compatibility limitations?

**Comment by pythonnxx** [comment]
not sure, I looked through all  the mods installed but I don't believe I have any mods that affect clothing items, maybe a setting in SVM? ill look into it some more

**Comment by tyfon7** [comment]
Mind sharing your mod list? Both server (user/mods) and client (bepinex/plugins)

**Comment by tyfon7** [comment]
Closing this no repro since I haven't heard back
