### ISSUE TITLE
[ Resolve conflict ] https://hub.sp-tarkov.com/files/file/2262-mergeconsumables/

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#60]
This mod is awesome - allows to combine 50/400 + 40/400 AFAKs to one AFAK 90/400 and so on.
But mod is pretty simple and requires to drag on drop on the item, so UIFixes uses that to feature "exchange places of the items"...

Actually i cant imagine good solution - both features are good, but maybe "if mod installed - prefer merge?"

**Comment by tyfon7** [comment]
Make sure you're on latest version of both, we made these work together last week.

**Comment by 6562680** [comment]
will check
