### ISSUE TITLE
[ Feature request ] "Next" offer in each row in flea view

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#65]
When create a weapon build we usually press "buy" button, and then bots can add order in EURO/USD instead of roubles. Would be great to have button "skip current offer" and show next one in that certain row.

**Comment by tyfon7** [comment]
I'm not sure I understand what you're asking for here. You want to skip a given offer for a build... so you can pay more money? The server returns the offers that are lowest.

**Comment by 6562680** [comment]
Almost :D I just want to pay roubles (i have for example 42 millions), but i have only 5000 EUR and i need it for SOLAR panel. So usually i need to press RMB to EUR offer then search offers by item to select next RUB price.

Would be great to see button "skip offer" to receive yes, next, a bit more expensive offer.

**Comment by tyfon7** [comment]
On the flea page for a build, you can still click the gear icon and limit the search to a specific currency

**Comment by 6562680** [comment]
thanks!
