### ISSUE TITLE
[ Additional mod request ] Advanced heal

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#66]
If you need extra money - contact my telegram @gzhegow or whatsapp (see github profile), if it's not 100$/per mod or something - I guess I could pay for. Sure - just for personal use, we play with friends in the evenings.

Need a simple mod that heals a certain percentage to all body parts when healing an certain body part. This is only about healing with a medkit, not other ways.

For example - I used CMS to heal my right arm. Now the right arm only has 1/25hp. I heal 24hp, and I want 2.4~3hp to bring to each other body part. The percentage should be configurable.

**Comment by tyfon7** [comment]
no thanks
