### ISSUE TITLE
Toggle only active Flashlight/Laser

### ISSUE THREAD

**Issue by B-u-z-z-T** [tyfon7/UIFixes#67]
When using more than one tactical mods, like laser and a seperate flashligth, rangefinder, whatever... - i never understood, why you'd toggle all tactical mods, even those, which are not active/enabled. So i have e.g. my X400/Baldr Pro (on) and my rangefinder (off, with laser off/not visible)  and toggle X400/Baldr Pro's mode from laser only, to Flashlight, it also toggles through the mode of the Rangefinder - which i would like to stay on the same mode - since it is not active - since, if i toggle off the Flashlight, it automatically switches on the rangefinder, but now the laser is visible (which i did not want). It especially creates trouble, when having different tactical mods, that have different mode-numbers.

_(Brainstorming)
This of course only tackles the problem, when switching between two tac-mods/states (both tactical mods at different states). If those two mods, with different mode-numbers are active at the same time, the same problem will still be occuring. Not sure, what could be a good solution to this, like setting up a "presets" (however that would look like). A simpler idea would be, to disable some tactical mods, from toggling through their mode (via hotkey). So if you e.g. have a flashlight with different modes and a laser, that has [visible, IR, ...] i might want to toggle through the flashlight modes, but NEVER (via hotkey) through the IR modes of the laser, when e.g. not wearing NVGs. You still could change modes via context menue. i am using "Item Context Menu Extended" to toggle the states, like light on, rangefinder off, since the usually have the same state, by default. some "lock mode" in the context menue could be nice.
Another thing could be, to being able to toggle between states, like if you have two tactical mods, one on, one off - you're never able to toggle to both being off. Might be helpful to toggle through those to states, but also one where all are off, but then you'd probably need one more, with both on, which would make it again just annoying._

**Comment by tyfon7** [comment]
You might not be aware but UI Fixes lets you quickbind individual tactical devices. So inspect your gun, mouse-over the flashlight/laser/etc, hit your quickbind (say, 4). Now 4 will toggle just that device, and shift-4 will change its mode. You can change shift to a different modifier key in the F12 menu.

**Comment by B-u-z-z-T** [comment]
Oooh, yeah, i indeed wasn't aware of that - nice feature! (and a much cleaner solution to my 'brainstorming' 👍🏻)
Is it possible to use different key(bind)s, like MouseButton2/3, without binding them to a slot (EFT keybind). Usually my slots are already filled with meds, (impact-)grenades, injectors,... . Also especially using configurable hotkey(combos) for switching state and mode? Like i personally usually switch state with MB2 and mode with MB3 (via EFT binds) - i'd use the UIFixes keybind for one tactical mod for MB3 for example, but only want to change the mode, without holding shift. But if that's too complicated or unnecessary effort (maybe i am the only one) - i can also create a AHK script, to rebind my mouse buttons.

Still toggling (EFT binds) the modes of only active (switched on) tactical mods, **could** still be interesting.

**Comment by tyfon7** [comment]
It doesn't work with totally custom keybinds because it uses the existing keybind messaging code, which allows it to properly trigger animations, follow rules for not doing two things at once, etc. 

I'd rather invest in more quickslots (which is not easy either, btw, lol) than try to get custom keybinds to work with this stuff.

Gonna close this one as not planned, but thanks for the suggestion and discussion.

**Comment by B-u-z-z-T** [comment]
Oh, true, more quickslots would be a much more versatile solution! But yeah, i can imagine, that's not trivial at all...

**Comment by B-u-z-z-T** [comment]
I just had another idea, since i am using your quickslot-solution for the selective control over one assigned e.g. light. - love it, btw!
I don't know, how the information about bound quickslots is stored and how and how fast this would be changeable via an event, called by the plugin, but:
Might it be possible to store several quickslot (double occupancy) binds manually (in the plugin) and change the EFT/vanilla quickslots accordingly, on the fly? Like, if i have two rifles, each with one light and one laser, and i would like to bind quickslot 4 (light) and 5 (laser) to both weapon's lights/lasers - the binding would still happen as usual, with hovering over the mod and pressing the quickslot hotkey, but this information will be stored in the plugin behind the scenes. Then in raid, depending on which weapon is equipped, the according stored quickslot-binds would be set/updated in EFT. Basically e.g. catching/storing the hotkey-bind-event and replaying/sending them according to equipped weapon. And the list should not overflow, with all mods in the stash or backpack, since those quickslots should only store information about mods on weapons, that are stored on the character's weapon slots (or on the character overall). Everything else can be deleted.

_If this could work at all,_ you could expand it, to quickslots, combined with shift/ctrl/alt. So then the manually stored quickbinds would be updating EFTs quickbinds on every shift/ctrl/alt-keypress, to according binds, and revert on release. But that depends on the responsiveness/performance, how realistic that would be.
As far as i imagine the only downside would be, that the quickslot's image would only show the last bound item, of course. So you'd have to recall those bound items on your own. I guess, on the item icon itself, could be a custom symbol, like the keysymbol, as if it is bound vanilla.

But yeah, let me know what you think, or if you already know, if it is (not) possible, or if you already came up with an idea for the quickslot-extension.
