### ISSUE TITLE
Flea market showing no offers after upgrading to 1.6.0

### ISSUE THREAD

**Issue by CrowDz11** [tyfon7/UIFixes#7]
[LogOutput.log](https://github.com/tyfon7/UIFixes/files/15477361/LogOutput.log)

**Comment by tyfon7** [comment]
Turns out this is actually a 3.8.0 -> 3.8.3 incompatibility. I'm using one of the new functions added since 3.8.0.

Strong recommend upgrading, it's easy and only takes a few seconds.
