### ISSUE TITLE
Feature Request: Improve dropdown behavior: Larger click area, close on click outside

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#71]
So basically, the ability to left click on the little square with the icon instead of having to click on the arrow button next to it in different menus such as the Generator one, or the Gun Modifying one. And for the Gun Modifying one, maybe the ability to click anywhere on the screen to hide the attachment selection menu.

![image](https://github.com/user-attachments/assets/3567fb7b-69f5-4494-8f20-4cad4bf87ded)

For example, in the image below, to click either on the square with the attachment already selected (DPCSM) for the menu to close, or to click around to close it.

![image](https://github.com/user-attachments/assets/3957a5c1-cf57-45ed-986c-b797b9629d55)

**Comment by tyfon7** [comment]
implemented in 2.5.2
