### ISSUE TITLE
Feature Request: Caching container location

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#72]
A feature that temporarily remembers the location of containers that have been previously opened in the stash. For example, if I was organizing my stash, then left to visit the trader, when I return to the stash or open it while at the trader's window, I want the specific container I was interacting with to be in the same open state as when I left it.

The location can be removed after a raid or after the client is restarted.

**Comment by tyfon7** [comment]
Closing this as simply too complicated and unlikely to happen. #91 may help somewhat (if I implement that...)
