### ISSUE TITLE
Wrong monitor location

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#77]
Sometimes, when tarkov starts, it confuses what monitor is which. I have 3 monitors, 3 different brands, one ultra wide 1440p, and two normal 1440p. I know this bug exists in Tarkov Live as well. When the bug happens it either launches Tarkov on my left or right monitor.

My monitors are setup like this, and the ultrawide is my main and the one I use for Tarkov as well.
![image](https://github.com/user-attachments/assets/85ae6477-0aaa-4d28-8612-019474cfdeb0)

I do not if you'd be willing to fix this, but I decided to try.
If you need additional info that I can give, feel free to tell me.

**Comment by tyfon7** [comment]
I've never had this issue, and I suspect it's very dependent on individual setups. Also likely more to do with unity than anything tarkov specific.
