### ISSUE TITLE
Feature Request: Better Crafting

### ISSUE THREAD

**Issue by LordHarkon** [tyfon7/UIFixes#78]
A feature that let's you craft multiple items from the same station and/or let's you craft multiple of the same craft.

For example, maybe I want to craft 8 Spark Plugs, but I don't wanna go take the items and start the craft each time one is finished, and I want to craft all 8 at the same time and collect all of them at the end.

**Comment by tyfon7** [comment]
Queuing up crafts is a cool idea but it's not just UI, it would require taking the items and storing them server side. Would be a cool stand-alone mod, but not a UI Fix.
