### ISSUE TITLE
[ Feature Request ] Changing mechanic checkbox for backpacks/vests

### ISSUE THREAD

**Issue by 6562680** [tyfon7/UIFixes#80]
You have a checkbox in the options like "exchange containers that can't be put inside" or something like that, but in reality, inside the shelter, exchanging wallets or cases is not mandatory for me (and even useless).

But inside the raid, exchanging backpacks to destructure weapons is a common problem for gaining experience. The same with unloading vests, when I don't have space for it - I have to drop it on the ground...

This was, in my opinion, a useless complication made by Buyanov, but maybe there are already checkboxes to do something about it?

I mean - armor can be replaced only because it has no slots for any items

Backpacks and vests are a bit of a different story... In raids most of the time. Because dragging an item onto a container icon (which is equipped) the game understands as "put the item inside". By the way, the grid allows the same thing, so maybe this behavior could be optimized, or (if possible) an additional drop (or changeable) zone without an icon could be added under the equipped item.

(Sorry for often created tickets, just trying to keep contact with a genius :D)

**Comment by tyfon7** [comment]
The reasoning behind not swapping containers in raid is to protect people from costly mistakes - it's far too easy to drag something onto your dogtag case and swap them without realizing it and then you've lost that.

That said, I think an exception could be made for *equipped* containers - allowing you to swap backpacks with bodies.

**Comment by 6562680** [comment]
Maybe so, also it could be backpacks/vests (items with cargo), but your case is better

**Comment by 6562680** [comment]
fix: equipped at corpse items. You can swap with backpack that you carry inside your current backpack, that matters

**Comment by tyfon7** [comment]
In next release: swapping incompat containers option will allow swapping of equipped gear even in raid. This will allow (for example) swapping a bigger backpack

**Comment by 6562680** [comment]
Well, 2.5.2 version is Posted on SPT Hub, but github release still 2.5.1
