### ISSUE TITLE
Enhancement: Weapon modding QOL

### ISSUE THREAD

**Issue by B-u-z-z-T** [tyfon7/UIFixes#84]
1. Since i seem to be a blind af dude, i tend to search the correct slot on the weapon. Some visual assist would be nice. Like if i drag'n'drop a pistolgrip onto the empty pistolgrip slot, it sometimes takes a while for me to find that slot, especially, when some other mods were being added, that add even more slots, so the icon/box/slot for the pistolgrip moved (even to the next line).
The idea is, that the compatible Slots would light up (just as compatible rigs/backpacks, if there is enough space). Also the slot, that is already taken, but is able to be swapped with the new e.g. pistolgrip would be nice.

2. Additionally INSANE would be, a visual on the preview-3d-model, for the modslot you are hovering above, where that slot belongs to. Usually no problem, since there is only one pistolgrip-, barrel-, etc. slot, but when there are multiple (usually tacitcal) slots, you don't know, to what physical place it belongs. (in the stash no problem, but midraid, when it takes time for the animation to dis-/assemble them). For empty slots it could be a bright/lit dot and for taken slots, the item, that is placed on the slot. (placed slots are much easier to distinguish though, obviously) But i guess that is not that simple and fast/responsive.

_I am not sure, if i should create another issue for that, since it has a connection to the example above:_

3. To the topic, updating 3d models, according to their modslots - it would be nice, if the weapons in raid (on dead bodies) would update, according to its slots. Ad-lib i am not sure, if the mods would update, which would be not that important to me, but the light/laser. Sometimes you get blinded or distracted from some dead bodies equipment, so i then open their weaponspecs and drop (via hotkey) their light or disable the light via (your) context-menu, but it won't be updated. You can 'force' an update, if you swap the weapon to a new slot on the body (if i recall correctly, directly discarding it, didn't update it - not sure), but it's kinda janky.

4. Another QOL change, based on the modding in raid (with or without leatherman), would be being able to discard/drop any weaponmod on equipped (on me or dead enemy) weapons. Since you are able to drag'n'drop those mods (e.g. the pistolgrip) it would be nice to contextmenu- or hotkey-discard the taken slot. Which would be helpful for faster looting or modding, midraid, between two weapons. For swapping mods, that are not interchangeable (because of compatibility on both slots) or directly discarding mods - e.g. the mag (which does work) and pistolgrip - to reduce the weapons size, and take it to the backpack.
(btw. with props'/dvize' "Props In-Raid Modding (PIRM)" this is possible, just fyi, if there would be a solution to be found)

**Comment by tyfon7** [comment]
1. Done in next release.
2. Cool idea, but yeah insane work. A bit outside what I can do.
3. I can't repro this... dead body with a laser on, if I discard/move the laser it's gone. Might be another mod you have messing with it?
4. I want to follow the "can't modify in hands" rule, because bypassing that causes weird issues (normally you would never be able to equip an incomplete weapon and the game never expects it). But I've changed it to only count *your* hands, so you'll be able to modify guns on bodies.

**Comment by B-u-z-z-T** [comment]
1. Noice!
2. From what i have seen in your plugin so far, i think you eventually _would_ have been able to 😁👍, but with way too much time and effort, i agree. Especially too much, for this tiny feature upgrade.
3. In case i described it poorly - i was talking about the weapon model on the map, on the body. Not about the preview model, in the inventory of the dead bot. But if we're on the same page - interesting, gotta check again then - maybe it's a fika thing, since i am usually session client (not host)
4. Yeah, though so, although the game could even handle the weapon in your hands equipped, without pistolgrip, i totally agree, that this should not work and is too 'dangerous' for any error/jank. This (only on other bodies) is a perfect trade-off!

Thanks, man!

_Btw, instead of requesting stuff all the time, as if you owed to implement/change anything - i'd contribute myself, if my skills would be sufficient. E.g. i tried to recompile "Boop's TagEverything" mod (since it could be nice, e.g. for the "inventory organizing features" mod for backpacks and rigs, pulling items in the stash), but i couldn't figure out, why the for 3.9.8 compiled mod, didn't do it, despite booting without any error. If this is an interesting feature, for you, it could be nice, to be integrated in UIFixes. (Boop sadly is offline, since April)_
