### ISSUE TITLE
Unable to Modfy Vital Parts on Equipped Weapons

### ISSUE THREAD

**Issue by Hazeofdream** [tyfon7/UIFixes#86]
"Modify Vital Parts during Raid" does not check compatibility with "Modify Equipped Weapons", so if you attempt to modify vital parts of an equipped weapon, this will fail as if you cannot modify vital parts, Probably not hard to fix but was confusing for me until i figured that out.

**Comment by tyfon7** [comment]
Intended, but I get that it's confusing. I'll look into updating the language in the settings to make it more clear.

The reason you can't modify equipped weapons in raid is the game has issues when you have an incomplete weapon equipped.
