### ISSUE TITLE
Game stuck on loading - ReflectionTypeLoadException

### ISSUE THREAD

**Issue by FaKL-Code** [tyfon7/UIFixes#9]
The server side mod is working fine, no exceptions or bugs, but the client side one is giving me the following error:

I get stuck on the loading screen (the little circle keep spinning)

![image](https://github.com/tyfon7/UIFixes/assets/81397044/f41a793a-8d45-4a36-977c-a71213ea936f)

Bepinex\LogOutput.log says:

```
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Tyfon.UIFixes, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
```
I'm using the following mods in my Bepinex:

```
ConfigurationManager.dll
CWX-GrassCutter.dll 
DrakiaXYZ-SearchOpenContainers.dll 
Endurance.dll 
Gaylatea-UseLooseLoot.dll 
HealingAutoCancel.dll 
InventoryOrganizingFeatures.dll 
LootValue.dll 
QuickThrowGrenades.dll 
StayInTarkov.dll 
Tyfon.UIFixes.dll 
VCQLQuestZones.dll 
AmandsGraphics.dll 
Arys-QuieterFaceshieldBreathing.dll 
BDSM.dll 
BossNotifier.dll 
CactusPie.RamCleanerInterval.dll
```

Could it be a bug or an incompatibility issue?

I'm not used to .NET stuff but I would suspect something about _UIFixes.AssemblyInfo.cs_, just don't know what could it be.

Let me know on discord if I can help with any more information.

<a href = "https://discordapp.com/users/389566109512237056">
    <img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white"/>
</a>

Edit:
```
SIT EFT Version: 0.14.1.3.29351
SIT Version: 1.10.8882.41069
SPT-AKI Version: 3.8.0.0
SIT Mod Version: 1.6.4
```

**Comment by tyfon7** [comment]
SPT 3.8.x uses EFT version 0.14.1.2.29197. I don't know how SIT works but if it uses EFT 0.14.1.3.29351, then unfortunately many many client mods will not work. Client mods work by using Harmony patches and reflection to insert code into the client - if the client code is different than what we expect, boom.

Frankly I'm surprised anything works at all if you're using SPT 3.8.x and that EFT version, but again I don't know how SIT works.

**Comment by FaKL-Code** [comment]
Yeah, many of those were a challenge to get working, some I even had to modify and recompile. Thanks anyway, I'll figure something out. So far, looking at the source code for a bit, I found out Aki.Reflection.dll/UnityEngine.UI.dll don't have some of the namespaces the mod uses, not sure I'm right about this but I'll give it a try to fix it.
