### ISSUE TITLE
UI Fixes disconnects remote players on FIKA dedicated client 

### ISSUE THREAD

**Issue by gnar-rip** [tyfon7/UIFixes#94]
Wasn't really sure how to title this but I will try to explain the best I can. I did some trouble shooting with the staff over at the FIKA discord as well and here is what we found:

Seperate dedicated machine for host, using FIKA dedicated plugin. Player 1 (me) and Player 2 (friend, playing remotely) are both able to connect to, and play solo on dedicated server. Player 1 is able to play solo with Dedicated Client on Dedicated Server, and also solo host. Player 2 is NOT able to play solo with Dedicated Client nor play with Player 1 on Dedicated Client, but can solo host on dedicated server.

Player 2 can load into Dedicated Client game with Player 1, but disconnects anywhere from 3-10 minutes.

Steps we took to recreate bug:

Uninstalled all mods, installed only ui-fixes with Fika Server 2.3.0, and Fika Dedicated 1.1.2, and Player 2 disconnects randomly anywhere from 3-10 minutes.

We also added our usual mod list back one by one, testing after every mod added and had no disconnects until ui-fixes was added.

Nothing weird in any of the logs, no errors thrown that I picked up on.

**Comment by tyfon7** [comment]
Can you check that both players and the dedi-client have the exact same UI Fixes settings (F12 menu)?

If the settings are different, things that are allowed on one client would be disallowed on another, causing issues. Since player 2 cannot play solo on the dedicated client, maybe player 2 has changed their settings?

**Comment by gnar-rip** [comment]
Dedi-client and both players fresh UI fixes, no changes made in F12 menu, and still disconnect after about 5 minutes. No errors in the logs, nothing out of the ordinary in either of our player.logs either.

**Comment by tyfon7** [comment]
If I understand the setup correctly, the issue arises when player 2 is not the host, in other words when player 2 has nonzero latency to the host client. 

Is the disconnected preceded by the game becoming unresponsive? It would make sense if UI Fixes is somehow hanging the game that a disconnect would follow. It doesn't make sense that the disconnect would happen without that - I really don't touch networking code.

**Comment by tyfon7** [comment]
Closing due to lack of response. Feel free to re-open if it's still happening and you have more information.
